envs:
  detect: &detect
    - USE_SSL=False
    - POSTGRES_IP=postgres

services:
  cockroach:
    command: "/usr/local/bin/cockroach start --insecure"
    driver: EXEC
  detect:
    image: 107849844305.dkr.ecr.eu-west-1.amazonaws.com/corti/detect-cpu:v1.1.0
    env: *detect
    volumes:
      - /opt/corti/data:/opt/corti/data
    # restart
    # depends_on
    # ports
    # stop_signal
  postgres:
    image: postgres
